### ISSUE TITLE
RabbitMQ consumer restart protocol keeps crashing threads

### ISSUE THREAD

**Issue by mennohie** [mennohie/wdm24-team9#23]
`2024-05-23 13:53:23 Traceback (most recent call last):
2024-05-23 13:53:23   File "/app/app.py", line 102, in <module>
2024-05-23 13:53:23     t.start()
2024-05-23 13:53:23   File "/usr/local/lib/python3.12/threading.py", line 987, in start
2024-05-23 13:53:23     raise RuntimeError("threads can only be started once")
2024-05-23 13:53:23 RuntimeError: threads can only be started once`

**Comment by janvandermeulen** [comment]
Fixed in pull request #27
